import { FieldMapperProperty, FieldMapper } from '@node-yalc/interfaces';
import { ClassType } from '@node-yalc/types/globals.js';
import { isClass } from '@node-yalc/utils/class.helper.js';
import { RelationType } from 'typeorm/metadata/types/RelationTypes.js';
import 'reflect-metadata';

export interface DstExtended {
  name: string;
  transformer: { (dstObj: Record<any, any>, srcValue: any): void };
}

export function isDstExtended(dst: string | DstExtended): dst is DstExtended {
  const _dst = dst as DstExtended;
  return !!_dst.name && !!_dst.transformer;
}

export interface YalcAgGridFieldMetadata extends Omit<
  FieldMapperProperty,
  'dst'
> {
  dst?: string | DstExtended;
  src?: string;

  /**
   * Sets the modality we want to retrieve the data
   *
   * * 'derived': the field exists on the datasource but is generated by an expression
   *  that can be defined in 'dst' (can be used for json fields or other syntax)
   * * 'regular (default)': the field exists on the datasource and is fetched regularly
   * * 'virtual' (not implemented): the field doesn't exist on the datasource and must be set programmatically
   *
   */
  mode?: 'derived' | 'regular' | 'virtual';

  /**
   * To specify if it's a resource that can be loaded with a dataLoader/join
   */
  relation?: {
    defaultValue?: any; // AgQueryParams<T> will be handled where it is needed or extended
    sourceKey: { dst: string; alias: string };
    /**
     * this is the field that will be used for both the dataloader and the join
     * For join: If the JoinColumn decorator exists on the same column, this key will be added
     * to the SQL `ON` condition
     */
    targetKey: { dst: string; alias: string };
    relationType: RelationType;
    type: { (): ClassType };
  };

  /**
   * Internally used
   */
  _propertyName?: string;
}

export const YALC_AGGRID_OBJECT_METADATA_KEY = Symbol('AGGRID_OBJECT_METADATA_KEY');
export const YALC_AGGRID_FIELD_METADATA_KEY = Symbol('AGGRID_FIELD_METADATA_KEY');

export function getPrototype(target: Record<string, unknown> | ClassType): any {
  /* istanbul ignore next */
  return isClass(target) || !target.prototype ? target : target.prototype;
}

export const YalcAgGridField = (
  options: YalcAgGridFieldMetadata = {} as any
): PropertyDecorator => {
  return (target: any, property: string | symbol) => {
    const classConstructor = target.constructor;
    const propertyName = property.toString();

    const metadata =
      Reflect.getMetadata(YALC_AGGRID_FIELD_METADATA_KEY, classConstructor) || {};

    // create new object reference to avoid this issue: https://github.com/rbuckton/reflect-metadata/issues/62
    const newMetadata: any = { ...metadata };

    newMetadata[propertyName] = {
      dst: propertyName,
      src: propertyName, // Note: the wrapper in nestjs can overwrite this with gqlOptions.name
      ...options,
      _propertyName: propertyName,
    };

    Reflect.defineMetadata(
      YALC_AGGRID_FIELD_METADATA_KEY,
      newMetadata,
      classConstructor,
    );
  };
};

export const getYalcAgGridFieldMetadataList = <T extends YalcAgGridFieldMetadata = YalcAgGridFieldMetadata>(
  target: Record<string, unknown> | ClassType,
): { [key: string]: T } | undefined => {
  return Reflect.getMetadata(YALC_AGGRID_FIELD_METADATA_KEY, getPrototype(target));
};

export const hasYalcAgGridFieldMetadataList = (
  target: Record<string, unknown> | ClassType,
): boolean => {
  return Reflect.hasMetadata(YALC_AGGRID_FIELD_METADATA_KEY, getPrototype(target));
};

export const getYalcAgGridFieldMetadata = <T extends YalcAgGridFieldMetadata = YalcAgGridFieldMetadata>(
  target: Record<string, unknown> | ClassType,
  propertyName: string | symbol,
): T | undefined => {
  const metadata = getYalcAgGridFieldMetadataList<T>(target);

  const name = propertyName.toString();

  if (!metadata || !metadata[name]) return undefined;

  return metadata[name];
};

export const hasYalcAgGridFieldMetadata = (
  target: Record<string, unknown> | ClassType,
  propertyName: string,
): boolean => {
  const metadata = Reflect.getMetadata(
    YALC_AGGRID_FIELD_METADATA_KEY,
    getPrototype(target),
  );

  return metadata && !!metadata[propertyName];
};

export const YalcAgGridObject = (options?: YalcAgGridObjectOptions): ClassDecorator => {
  return (target) => {
    let metadata = options ?? {};

    if (metadata.copyFrom) {
      const copyFrom = metadata.copyFrom;
      metadata = { ...metadata, ...getYalcAgGridObjectMetadata(copyFrom) };

      const fieldMetadata = { ...getYalcAgGridFieldMetadataList(copyFrom) };

      Reflect.defineMetadata(YALC_AGGRID_FIELD_METADATA_KEY, fieldMetadata, target);
    }

    Reflect.defineMetadata(YALC_AGGRID_OBJECT_METADATA_KEY, metadata, target);
  };
};

export const getYalcAgGridObjectMetadata = (
  target: Record<string, unknown> | ClassType,
): FilterOption => {
  return Reflect.getMetadata(YALC_AGGRID_OBJECT_METADATA_KEY, getPrototype(target));
};

export const hasYalcAgGridObjectMetadata = (
  target: Record<string, unknown> | ClassType,
): boolean => {
  return Reflect.hasMetadata(YALC_AGGRID_OBJECT_METADATA_KEY, getPrototype(target));
};

/**
 * The options below allow to implement an include/exclude mechanism for mapped fields.
 * It can be used to deny the usage of certain fields
 */
export enum FilterOptionType {
  /** include fields specified inside the array of fields and exclude all the others */
  INCLUDE = 'include',
  /** exclude fields specified inside the array of fields and include all the others */
  EXCLUDE = 'exclude',
}

export type FilterOption = {
  type: FilterOptionType;
  fields: string[];
};

export type YalcAgGridObjectOptions = {
  /**
   * Copy agGrid decorator metadata from another class
   * Useful when the classes are similar but they don't share the prototype
   * E.G. when you use OmitType or similar techniques
   */
  copyFrom?: ClassType;
  filters?: FilterOption;
};

export interface FieldAndFilterMapper {
  field: FieldMapper;
  //When filterOption is set we can manage filters on fields with an inclusion/exclusion strategy
  filterOption?: FilterOption;
  extraInfo?: { [key: string]: any };
}
