import { BadGatewayException, BadRequestException, ConflictException, ForbiddenException, GatewayTimeoutException, GoneException, HttpException, InternalServerErrorException, MethodNotAllowedException, MisdirectedException, NotAcceptableException, NotFoundException, NotImplementedException, PayloadTooLargeException, PreconditionFailedException, RequestTimeoutException, ServiceUnavailableException, UnauthorizedException, UnprocessableEntityException, UnsupportedMediaTypeException } from '@nestjs/common';
export declare const HttpStatusCodes: Record<string, any>;
export type HttpStatusCodes = (typeof HttpStatusCodes)[keyof typeof HttpStatusCodes];
export declare const getHttpStatusDescription: (status: HttpStatusCodes, fallbackDescription?: string) => string;
export declare const httpExceptionStatusCodes: {
    [BadRequestException.name]: any;
    [UnauthorizedException.name]: any;
    [ForbiddenException.name]: any;
    [NotFoundException.name]: any;
    [MethodNotAllowedException.name]: any;
    [NotAcceptableException.name]: any;
    [RequestTimeoutException.name]: any;
    [ConflictException.name]: any;
    [GoneException.name]: any;
    [PreconditionFailedException.name]: any;
    [PayloadTooLargeException.name]: any;
    [UnsupportedMediaTypeException.name]: any;
    [UnprocessableEntityException.name]: any;
    [InternalServerErrorException.name]: any;
    [NotImplementedException.name]: any;
    [BadGatewayException.name]: any;
    [ServiceUnavailableException.name]: any;
    [GatewayTimeoutException.name]: any;
    [HttpException.name]: any;
    [MisdirectedException.name]: any;
};
